services:
  mysqldb:
    container_name: mysqlcontainer
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ~/database:/var/lib/mysql
    ports:
      - :3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: booksdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Ha77a01*!
      MYSQL_ROOT_PASSWORD: Ha77a01*!
      SERVICE_TAGS: prod 
      SERVICE_NAME: mysqldb 
    networks:
      - internalnet 

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - :3000
    expose:
      - 3000
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_USER: admin
      DB_PASSWORD: 'Ha77a01*!'
      DB_NAME: booksdb
      DB_PORT: 3006
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
      SERVICE_TAGS: prod 
      SERVICE_NAME: nodeappservice
    networks:
      - internalnet


networks:
  internalnet:
    driver: bridge